### ISSUE TITLE
Upgrade to actix-web 2.0 now that it's generally available

### ISSUE THREAD

**Issue by akesling** [actix/actix-protobuf#7]
I tried to upgrade a project of mine to using actix-web 2.0 and actix-protobuf turned out to be the primary blocker for that migration.  I suspect many others will find themselves in that position soon as well.

Are there plans in the works?

**Comment by fafhrd91** [comment]
Not really, unless someone provides pr

**Comment by akesling** [comment]
@JohnTitor when should we expect a release that includes this?

**Comment by JohnTitor** [comment]
I'd like to release it ASAP, but if possible, it's ideal to update bytes to 0.5 (blocked by prost) before doing since I think it affects users using bytes 0.4 or lower.
